# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  pool: 5
  timeout: 5000
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: bdostats-development
  username: bdostats
  password: bdostats

