# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2ac46edc35ed9ddad80234f33d85b515701d0cbcb9b413611c2625a7e12cb8de3feada264e8d6d8a77dc6c585e02f6d7026fc75d27e591711bea6635af06003

test:
  secret_key_base: 3b3e85efca4528f8e65ae30c551375bac6e72d22b5c2278121eadb8393b34213b739f823933c166fe705668079e3479885ce0f51cfa3c239bb8e264efef5c920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
